import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Manrope, Roboto_Serif } from "next/font/google";
import "./globals.css";

const manrope = Manrope({
  variable: "--font-manrope",
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

const robotoSerrif = Roboto_Serif({
  weight: ["300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "WellnessmClear",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(robotoSerrif.variable, manrope.className)}>
        {children}
      </body>
    </html>
  );
}
